### ISSUE TITLE
Add unit of measure (C/F) to met_no weather plugin

### ISSUE THREAD

**Issue by ZubaZ21** [txoof/epd_display#60] opened 2022-02-28 01:33 UTC
It appears that the plugin might be modified to switch between celsius to fahrenheit but moving that to the plugin config would be significantly easier for an end user.  (I am the end user. :(  )

**Comment by aaronr8684** [comment] 2022-02-28 03:49
Duplicate of #55

**Comment by txoof** [comment] 2022-02-28 06:56
resolved: 59937918563fc88d130363c2f46a3c801edfd8b5

use the following in `paperpi.ini`:
```
temp_units = celsius
rain_units = mm 
```

**Closed by txoof** 2022-02-28 06:56 UTC
